/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryShop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;


/**
 *
 * @author Bogdan
 */
public class Register extends javax.swing.JFrame  {

    /**
     * Creates new form Register
     */
   
    Connection conn=null;
    Connection conn1=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
    ResultSet rs=null;
    ResultSet rs1=null;
    public Register() {
        this.pst1 = null;
        initComponents();
        conn1=MysqlConnect_1.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRegisterLastName = new javax.swing.JTextField();
        txtRegisterPhoneNumber = new javax.swing.JTextField();
        txtRegisterPassword = new javax.swing.JPasswordField();
        txtRegisterRetypePassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnRegisterBack = new javax.swing.JButton();
        lbRegisterEmail = new javax.swing.JLabel();
        txtRegisterEmail = new javax.swing.JTextField();
        lbRegisterPhoneNumber = new javax.swing.JLabel();
        lbRegisterFirstName = new javax.swing.JLabel();
        lbRegisterPasswordVrf = new javax.swing.JLabel();
        lbRegisterRetypeVrf = new javax.swing.JLabel();
        lbRegisterLastName = new javax.swing.JLabel();
        txtRegisterFirstName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Register");

        jLabel1.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Password");

        jLabel6.setText("Retype Password");

        jLabel7.setText("Email");

        btnRegisterBack.setBackground(new java.awt.Color(51, 153, 255));
        btnRegisterBack.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnRegisterBack.setText("Back");
        btnRegisterBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterBackActionPerformed(evt);
            }
        });

        lbRegisterEmail.setForeground(new java.awt.Color(255, 0, 0));

        lbRegisterPhoneNumber.setForeground(new java.awt.Color(255, 0, 0));

        lbRegisterFirstName.setForeground(new java.awt.Color(255, 0, 0));

        lbRegisterPasswordVrf.setForeground(new java.awt.Color(255, 0, 0));

        lbRegisterRetypeVrf.setForeground(new java.awt.Color(255, 0, 0));

        lbRegisterLastName.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegisterBack)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegisterLastName)
                            .addComponent(txtRegisterPhoneNumber)
                            .addComponent(txtRegisterPassword)
                            .addComponent(txtRegisterRetypePassword)
                            .addComponent(txtRegisterEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtRegisterFirstName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRegisterEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbRegisterPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRegisterFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbRegisterPasswordVrf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbRegisterRetypeVrf, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 21, Short.MAX_VALUE))
                            .addComponent(lbRegisterLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbRegisterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRegisterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegisterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbRegisterLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbRegisterEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRegisterEmail))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRegisterPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRegisterPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRegisterPasswordVrf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegisterRetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRegisterRetypeVrf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnRegisterBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterBackActionPerformed
        // TODO add your handling code here:
        dispose();
        Interfata s= new Interfata();
        s.setVisible(true);
        
        
    }//GEN-LAST:event_btnRegisterBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.pst=null;
        conn=MysqlConnect_1.ConnecrDb();
        if(((txtRegisterEmail.getText().endsWith("@yahoo.com")||txtRegisterEmail.getText().endsWith("@gmail.com"))&&txtRegisterEmail.getText().length()>13)
            &&((txtRegisterPhoneNumber.getText()).length()== 10&&txtRegisterPhoneNumber.getText().startsWith("07"))
                &&(!txtRegisterFirstName.getText().contains(" "))&&(txtRegisterPassword.getText().equals(txtRegisterRetypePassword.getText()))
                &&(txtRegisterPassword.getText().length()>5&&!(txtRegisterPassword.getText().contains(" ")))&&(txtRegisterLastName.getText().length()>=3))
        {lbRegisterEmail.setText("Ok");
        lbRegisterFirstName.setText("Ok");
        lbRegisterPhoneNumber.setText("Ok");
        lbRegisterPasswordVrf.setText("Ok");
        lbRegisterRetypeVrf.setText("Ok");
        lbRegisterLastName.setText("Ok");
        
        String sql1="insert into userss(user_id,user_first,user_last,email,nr_telefon,permisie,password) values ((select max(user_id) from userss)+1,?,?,?,?,'PowerUser',?)";
        
       //String sql2="select max(user_id) from userss";
       PreparedStatement preparedStmt;
        try{
           
            preparedStmt = conn.prepareStatement(sql1);
            preparedStmt.setString(1, txtRegisterFirstName.getText());
            preparedStmt.setString(2, txtRegisterLastName.getText());
            preparedStmt.setString(3, txtRegisterEmail.getText());
            preparedStmt.setString(4, txtRegisterPhoneNumber.getText());
            preparedStmt.setString(5, txtRegisterPassword.getText());
            preparedStmt.executeUpdate();
            
        }catch (SQLException ex) {
        Logger.getLogger("MyConnection").log(Level.SEVERE, null, ex);
        
    }
        dispose();
        Interfata s= new Interfata();
        s.setVisible(true);
        }
        
        if(lbRegisterEmail.getText().equals("Ok")&&lbRegisterFirstName.getText().equals("Ok")
            &&lbRegisterPhoneNumber.getText().equals("Ok")&&lbRegisterPasswordVrf.getText().equals("Ok")&&lbRegisterRetypeVrf.getText().equals("Ok")&&lbRegisterLastName.getText().equals("Ok"))
        {
            
        
    }//GEN-LAST:event_jButton1ActionPerformed
/*  */      
        else
           if((!(txtRegisterEmail.getText().endsWith("@yahoo.com")) || (!(txtRegisterEmail.getText().endsWith("@gmail.com"))))&&txtRegisterEmail.getText().length()<13)
           { lbRegisterEmail.setText("Invalid Email"); }
        
           if((txtRegisterPhoneNumber.getText()).length()!= 10||!txtRegisterPhoneNumber.getText().startsWith("07")){
                lbRegisterPhoneNumber.setText("Invalid Number");}
           if(txtRegisterFirstName.getText().contains(" ")||(txtRegisterFirstName.getText().length()==0)){
               lbRegisterFirstName.setText("Invalid First Name"); }
           if(txtRegisterPassword.getText().length()<=5||(txtRegisterPassword.getText().contains(" "))){
               lbRegisterPasswordVrf.setText("Invalid Password");}
           if(txtRegisterLastName.getText().length()<3){
           lbRegisterLastName.setText("Invalid Last Name");}
           if(!txtRegisterPassword.getText().equals(txtRegisterRetypePassword.getText())){
                lbRegisterRetypeVrf.setText("Retype again");}
           
           
           
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbRegisterEmail;
    private javax.swing.JLabel lbRegisterFirstName;
    private javax.swing.JLabel lbRegisterLastName;
    private javax.swing.JLabel lbRegisterPasswordVrf;
    private javax.swing.JLabel lbRegisterPhoneNumber;
    private javax.swing.JLabel lbRegisterRetypeVrf;
    private javax.swing.JTextField txtRegisterEmail;
    private javax.swing.JTextField txtRegisterFirstName;
    private javax.swing.JTextField txtRegisterLastName;
    private javax.swing.JPasswordField txtRegisterPassword;
    private javax.swing.JTextField txtRegisterPhoneNumber;
    private javax.swing.JPasswordField txtRegisterRetypePassword;
    // End of variables declaration//GEN-END:variables
}
